# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axiom < Formula
  desc "The immutable system of truth for AI agent style guides and coding standards."
  homepage "https://github.com/aetosdios27/axiom-core"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aetosdios27/axiom-core/releases/download/v1.0.0/axiom_Darwin_x86_64.tar.gz"
      sha256 "c7e4426824f2d7767df5d138550ed4300ffc18cf3827d641d421dfe13edcdeee"

      define_method(:install) do
        bin.install "axiom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aetosdios27/axiom-core/releases/download/v1.0.0/axiom_Darwin_arm64.tar.gz"
      sha256 "64486b44bdad9ada31536667b91712de6a64b26cdfc6a80fa82c903c63ecaaad"

      define_method(:install) do
        bin.install "axiom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aetosdios27/axiom-core/releases/download/v1.0.0/axiom_Linux_x86_64.tar.gz"
      sha256 "525911155cf4c8faea9167c1c251f6c5df3d8a53a6ba1860b6e260046cc8b669"
      define_method(:install) do
        bin.install "axiom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aetosdios27/axiom-core/releases/download/v1.0.0/axiom_Linux_arm64.tar.gz"
      sha256 "5e86447c7249c0b1b04ab303768c6c28ec095941c39805f3458ce538f7939a29"
      define_method(:install) do
        bin.install "axiom"
      end
    end
  end

  test do
    system "#{bin}/axiom version"
  end
end
