# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axiom < Formula
  desc "The immutable system of truth for AI agent style guides and coding standards."
  homepage "https://github.com/aetosdios27/axiom-core"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aetosdios27/axiom-core/releases/download/v1.0.3/axiom_Darwin_x86_64.tar.gz"
      sha256 "4974ae267dd5c49d526876317fea6c3fecc7fc496513098f11e527889b53998b"

      define_method(:install) do
        bin.install "axiom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aetosdios27/axiom-core/releases/download/v1.0.3/axiom_Darwin_arm64.tar.gz"
      sha256 "9b1ad782296df1279f485e97876771fb1ff4465cc8122bf55d69c7a7c002d81b"

      define_method(:install) do
        bin.install "axiom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aetosdios27/axiom-core/releases/download/v1.0.3/axiom_Linux_x86_64.tar.gz"
      sha256 "6eaf9d068be83b8bc7066e753a6bd53d638b4e5ae2fc1ee9dc9654ab2ef128c5"
      define_method(:install) do
        bin.install "axiom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aetosdios27/axiom-core/releases/download/v1.0.3/axiom_Linux_arm64.tar.gz"
      sha256 "bb419c048042dccf6ccd25332fdf4950fdf3658bdcafc8deb6be9f4ef80cce38"
      define_method(:install) do
        bin.install "axiom"
      end
    end
  end

  test do
    system "#{bin}/axiom version"
  end
end
